### ISSUE TITLE
Please upgrade code to newer Bazel versions?

### ISSUE THREAD

**Issue by divyekapoor** [meetup/rules_openapi#21]
```
ERROR: /private/var/tmp/_bazel_dkapoor/3baa8d03663d350dcfcfed1ae0b311db/external/io_bazel_rules_openapi/openapi/openapi.bzl:5:5: //external:io_bazel_rules_openapi_io_swagger_swagger_codegen_cli: no such attribute 'sha256' in 'maven_jar' rule
```

maven_jar rule is deprecated in favor of rules_jvm_external
https://docs.bazel.build/versions/master/be/workspace.html#maven_jar

The above works with bazel 0.23, fails with bazel 0.29.1-homebrew

**Comment by chenrui333** [comment]
@divyekapoor I have just removed `maven_jar` rule, let me know if it works for you. Thanks for the report.
