### ISSUE TITLE
OpenAPITools/openapi-generator-bazel

### ISSUE THREAD

**Issue by yishanhe** [meetup/rules_openapi#33]
what is the difference between this repo and https://github.com/OpenAPITools/openapi-generator-bazel. are they two individual bazel rule project for openapi generator? or difference scopes? I found committers are almost same group of people.  Thanks.

**Comment by chenrui333** [comment]
@yishanhe the openapi work was after this rules_openapi, I can perceive them pretty similar.

Note, the underlying openapi is different, that project is actually a spin off I think.

At meetup, we are currently still use the old openapi, that is why this project is still maintained and used.

**Comment by chenrui333** [comment]
relates to #27
